version: "3.9"

services:
  frontend:
    image: ssayan/devops-portfolio:latest
    container_name: devops-portfolio-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    restart: always
    networks:
      - portfolio-net

networks:
  portfolio-net:
    driver: bridge
